name: Dev Branch Release

on:
    push:
        branches:
            - dev

jobs:
    build_dev:
        name: Build Docker image for dev branch
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Set up Docker tag
              id: docker_tag
              run: echo "tag=dev" >> $GITHUB_OUTPUT

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag zbejas/ad_fontem:dev

            - name: Push the Docker image
              run: docker push zbejas/ad_fontem:dev
